# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aggregation_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18\x61ggregation_server.proto\x12\x12\x61ggregation_server">\n\x10\x43onfigureRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x16\n\x0enum_of_workers\x18\x02 \x01(\x05"#\n\x11\x43onfigureResponse\x12\x0e\n\x06status\x18\x01 \x01(\t"Q\n\x10\x41ggregateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x18\n\x10\x61ggregation_type\x18\x02 \x01(\t\x12\x0f\n\x07vectors\x18\x03 \x03(\x02"#\n\x11\x41ggregateResponse\x12\x0e\n\x06result\x18\x01 \x03(\x02"$\n\x0e\x43leanupRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t"!\n\x0f\x43leanupResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9b\x02\n\x11\x41ggregationServer\x12X\n\tConfigure\x12$.aggregation_server.ConfigureRequest\x1a%.aggregation_server.ConfigureResponse\x12X\n\tAggregate\x12$.aggregation_server.AggregateRequest\x1a%.aggregation_server.AggregateResponse\x12R\n\x07\x43leanup\x12".aggregation_server.CleanupRequest\x1a#.aggregation_server.CleanupResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "aggregation_server_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CONFIGUREREQUEST"]._serialized_start = 48
    _globals["_CONFIGUREREQUEST"]._serialized_end = 110
    _globals["_CONFIGURERESPONSE"]._serialized_start = 112
    _globals["_CONFIGURERESPONSE"]._serialized_end = 147
    _globals["_AGGREGATEREQUEST"]._serialized_start = 149
    _globals["_AGGREGATEREQUEST"]._serialized_end = 230
    _globals["_AGGREGATERESPONSE"]._serialized_start = 232
    _globals["_AGGREGATERESPONSE"]._serialized_end = 267
    _globals["_CLEANUPREQUEST"]._serialized_start = 269
    _globals["_CLEANUPREQUEST"]._serialized_end = 305
    _globals["_CLEANUPRESPONSE"]._serialized_start = 307
    _globals["_CLEANUPRESPONSE"]._serialized_end = 340
    _globals["_AGGREGATIONSERVER"]._serialized_start = 343
    _globals["_AGGREGATIONSERVER"]._serialized_end = 626
# @@protoc_insertion_point(module_scope)
