# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import aggregation_server_pb2 as aggregation__server__pb2


class AggregationServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
            "/aggregation_server.AggregationServer/Configure",
            request_serializer=aggregation__server__pb2.ConfigureRequest.SerializeToString,
            response_deserializer=aggregation__server__pb2.ConfigureResponse.FromString,
            _registered_method=True,
        )
        self.Unregister = channel.unary_unary(
            "/aggregation_server.AggregationServer/Unregister",
            request_serializer=aggregation__server__pb2.UnregisterRequest.SerializeToString,
            response_deserializer=aggregation__server__pb2.UnregisterResponse.FromString,
            _registered_method=True,
        )
        self.Aggregate = channel.unary_unary(
            "/aggregation_server.AggregationServer/Aggregate",
            request_serializer=aggregation__server__pb2.AggregateRequest.SerializeToString,
            response_deserializer=aggregation__server__pb2.AggregateResponse.FromString,
            _registered_method=True,
        )
        self.AggregateBatch = channel.unary_unary(
            "/aggregation_server.AggregationServer/AggregateBatch",
            request_serializer=aggregation__server__pb2.AggregateBatchRequest.SerializeToString,
            response_deserializer=aggregation__server__pb2.AggregateBatchResponse.FromString,
            _registered_method=True,
        )
        self.Cleanup = channel.unary_unary(
            "/aggregation_server.AggregationServer/Cleanup",
            request_serializer=aggregation__server__pb2.CleanupRequest.SerializeToString,
            response_deserializer=aggregation__server__pb2.CleanupResponse.FromString,
            _registered_method=True,
        )


class AggregationServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Unregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Aggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AggregateBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Cleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AggregationServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Configure": grpc.unary_unary_rpc_method_handler(
            servicer.Configure,
            request_deserializer=aggregation__server__pb2.ConfigureRequest.FromString,
            response_serializer=aggregation__server__pb2.ConfigureResponse.SerializeToString,
        ),
        "Unregister": grpc.unary_unary_rpc_method_handler(
            servicer.Unregister,
            request_deserializer=aggregation__server__pb2.UnregisterRequest.FromString,
            response_serializer=aggregation__server__pb2.UnregisterResponse.SerializeToString,
        ),
        "Aggregate": grpc.unary_unary_rpc_method_handler(
            servicer.Aggregate,
            request_deserializer=aggregation__server__pb2.AggregateRequest.FromString,
            response_serializer=aggregation__server__pb2.AggregateResponse.SerializeToString,
        ),
        "AggregateBatch": grpc.unary_unary_rpc_method_handler(
            servicer.AggregateBatch,
            request_deserializer=aggregation__server__pb2.AggregateBatchRequest.FromString,
            response_serializer=aggregation__server__pb2.AggregateBatchResponse.SerializeToString,
        ),
        "Cleanup": grpc.unary_unary_rpc_method_handler(
            servicer.Cleanup,
            request_deserializer=aggregation__server__pb2.CleanupRequest.FromString,
            response_serializer=aggregation__server__pb2.CleanupResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "aggregation_server.AggregationServer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    if hasattr(server, "add_registered_method_handlers"):
        server.add_registered_method_handlers(
            "aggregation_server.AggregationServer", rpc_method_handlers
        )


# This class is part of an EXPERIMENTAL API.
class AggregationServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Configure(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aggregation_server.AggregationServer/Configure",
            aggregation__server__pb2.ConfigureRequest.SerializeToString,
            aggregation__server__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Unregister(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aggregation_server.AggregationServer/Unregister",
            aggregation__server__pb2.UnregisterRequest.SerializeToString,
            aggregation__server__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Aggregate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aggregation_server.AggregationServer/Aggregate",
            aggregation__server__pb2.AggregateRequest.SerializeToString,
            aggregation__server__pb2.AggregateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AggregateBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aggregation_server.AggregationServer/AggregateBatch",
            aggregation__server__pb2.AggregateBatchRequest.SerializeToString,
            aggregation__server__pb2.AggregateBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Cleanup(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aggregation_server.AggregationServer/Cleanup",
            aggregation__server__pb2.CleanupRequest.SerializeToString,
            aggregation__server__pb2.CleanupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
