#!/usr/bin/env bash
if [ -f "$CREDENTIALS_CONFIG_FOLDER/monetdb_password.sh" ]; then
    source $CREDENTIALS_CONFIG_FOLDER/monetdb_password.sh
fi
echo "
DB_IP = \"$DB_IP\"
DB_PORT = $DB_PORT
DB_NAME = \"$DB_NAME\"
MONETDB_ADMIN_USERNAME = \"$MONETDB_ADMIN_USERNAME\"
MONETDB_LOCAL_USERNAME = \"$MONETDB_LOCAL_USERNAME\"
MONETDB_LOCAL_PASSWORD = \"$MONETDB_LOCAL_PASSWORD\"
MONETDB_PUBLIC_USERNAME = \"$MONETDB_PUBLIC_USERNAME\"
MONETDB_PUBLIC_PASSWORD = \"$MONETDB_PUBLIC_PASSWORD\"" > "/home/config.toml"
tail -f /dev/null