# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in worker_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorkerInfo = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/GetWorkerInfo",
            request_serializer=worker__pb2.GetWorkerInfoRequest.SerializeToString,
            response_deserializer=worker__pb2.GetWorkerInfoResponse.FromString,
            _registered_method=True,
        )
        self.ListDatasetsPerDataModel = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/ListDatasetsPerDataModel",
            request_serializer=worker__pb2.ListDatasetsPerDataModelRequest.SerializeToString,
            response_deserializer=worker__pb2.ListDatasetsPerDataModelResponse.FromString,
            _registered_method=True,
        )
        self.GetDataModelCdes = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/GetDataModelCdes",
            request_serializer=worker__pb2.GetDataModelRequest.SerializeToString,
            response_deserializer=worker__pb2.GetDataModelCdesResponse.FromString,
            _registered_method=True,
        )
        self.GetDataModelAttributes = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/GetDataModelAttributes",
            request_serializer=worker__pb2.GetDataModelRequest.SerializeToString,
            response_deserializer=worker__pb2.GetDataModelAttributesResponse.FromString,
            _registered_method=True,
        )
        self.Healthcheck = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/Healthcheck",
            request_serializer=worker__pb2.HealthcheckRequest.SerializeToString,
            response_deserializer=worker__pb2.HealthcheckResponse.FromString,
            _registered_method=True,
        )
        self.StartFlowerClient = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/StartFlowerClient",
            request_serializer=worker__pb2.StartFlowerClientRequest.SerializeToString,
            response_deserializer=worker__pb2.StartFlowerClientResponse.FromString,
            _registered_method=True,
        )
        self.StartFlowerServer = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/StartFlowerServer",
            request_serializer=worker__pb2.StartFlowerServerRequest.SerializeToString,
            response_deserializer=worker__pb2.StartFlowerServerResponse.FromString,
            _registered_method=True,
        )
        self.StopFlowerClient = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/StopFlowerClient",
            request_serializer=worker__pb2.StopFlowerProcessRequest.SerializeToString,
            response_deserializer=worker__pb2.StopFlowerProcessResponse.FromString,
            _registered_method=True,
        )
        self.StopFlowerServer = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/StopFlowerServer",
            request_serializer=worker__pb2.StopFlowerProcessRequest.SerializeToString,
            response_deserializer=worker__pb2.StopFlowerProcessResponse.FromString,
            _registered_method=True,
        )
        self.GarbageCollect = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/GarbageCollect",
            request_serializer=worker__pb2.GarbageCollectRequest.SerializeToString,
            response_deserializer=worker__pb2.GarbageCollectResponse.FromString,
            _registered_method=True,
        )
        self.RunUdf = channel.unary_unary(
            "/exaflow.worker.api.WorkerService/RunUdf",
            request_serializer=worker__pb2.RunUdfRequest.SerializeToString,
            response_deserializer=worker__pb2.RunUdfResponse.FromString,
            _registered_method=True,
        )


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWorkerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListDatasetsPerDataModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDataModelCdes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDataModelAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Healthcheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartFlowerClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartFlowerServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopFlowerClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopFlowerServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GarbageCollect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RunUdf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetWorkerInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetWorkerInfo,
            request_deserializer=worker__pb2.GetWorkerInfoRequest.FromString,
            response_serializer=worker__pb2.GetWorkerInfoResponse.SerializeToString,
        ),
        "ListDatasetsPerDataModel": grpc.unary_unary_rpc_method_handler(
            servicer.ListDatasetsPerDataModel,
            request_deserializer=worker__pb2.ListDatasetsPerDataModelRequest.FromString,
            response_serializer=worker__pb2.ListDatasetsPerDataModelResponse.SerializeToString,
        ),
        "GetDataModelCdes": grpc.unary_unary_rpc_method_handler(
            servicer.GetDataModelCdes,
            request_deserializer=worker__pb2.GetDataModelRequest.FromString,
            response_serializer=worker__pb2.GetDataModelCdesResponse.SerializeToString,
        ),
        "GetDataModelAttributes": grpc.unary_unary_rpc_method_handler(
            servicer.GetDataModelAttributes,
            request_deserializer=worker__pb2.GetDataModelRequest.FromString,
            response_serializer=worker__pb2.GetDataModelAttributesResponse.SerializeToString,
        ),
        "Healthcheck": grpc.unary_unary_rpc_method_handler(
            servicer.Healthcheck,
            request_deserializer=worker__pb2.HealthcheckRequest.FromString,
            response_serializer=worker__pb2.HealthcheckResponse.SerializeToString,
        ),
        "StartFlowerClient": grpc.unary_unary_rpc_method_handler(
            servicer.StartFlowerClient,
            request_deserializer=worker__pb2.StartFlowerClientRequest.FromString,
            response_serializer=worker__pb2.StartFlowerClientResponse.SerializeToString,
        ),
        "StartFlowerServer": grpc.unary_unary_rpc_method_handler(
            servicer.StartFlowerServer,
            request_deserializer=worker__pb2.StartFlowerServerRequest.FromString,
            response_serializer=worker__pb2.StartFlowerServerResponse.SerializeToString,
        ),
        "StopFlowerClient": grpc.unary_unary_rpc_method_handler(
            servicer.StopFlowerClient,
            request_deserializer=worker__pb2.StopFlowerProcessRequest.FromString,
            response_serializer=worker__pb2.StopFlowerProcessResponse.SerializeToString,
        ),
        "StopFlowerServer": grpc.unary_unary_rpc_method_handler(
            servicer.StopFlowerServer,
            request_deserializer=worker__pb2.StopFlowerProcessRequest.FromString,
            response_serializer=worker__pb2.StopFlowerProcessResponse.SerializeToString,
        ),
        "GarbageCollect": grpc.unary_unary_rpc_method_handler(
            servicer.GarbageCollect,
            request_deserializer=worker__pb2.GarbageCollectRequest.FromString,
            response_serializer=worker__pb2.GarbageCollectResponse.SerializeToString,
        ),
        "RunUdf": grpc.unary_unary_rpc_method_handler(
            servicer.RunUdf,
            request_deserializer=worker__pb2.RunUdfRequest.FromString,
            response_serializer=worker__pb2.RunUdfResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "exaflow.worker.api.WorkerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "exaflow.worker.api.WorkerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWorkerInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/GetWorkerInfo",
            worker__pb2.GetWorkerInfoRequest.SerializeToString,
            worker__pb2.GetWorkerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListDatasetsPerDataModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/ListDatasetsPerDataModel",
            worker__pb2.ListDatasetsPerDataModelRequest.SerializeToString,
            worker__pb2.ListDatasetsPerDataModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDataModelCdes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/GetDataModelCdes",
            worker__pb2.GetDataModelRequest.SerializeToString,
            worker__pb2.GetDataModelCdesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDataModelAttributes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/GetDataModelAttributes",
            worker__pb2.GetDataModelRequest.SerializeToString,
            worker__pb2.GetDataModelAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Healthcheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/Healthcheck",
            worker__pb2.HealthcheckRequest.SerializeToString,
            worker__pb2.HealthcheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartFlowerClient(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/StartFlowerClient",
            worker__pb2.StartFlowerClientRequest.SerializeToString,
            worker__pb2.StartFlowerClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartFlowerServer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/StartFlowerServer",
            worker__pb2.StartFlowerServerRequest.SerializeToString,
            worker__pb2.StartFlowerServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopFlowerClient(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/StopFlowerClient",
            worker__pb2.StopFlowerProcessRequest.SerializeToString,
            worker__pb2.StopFlowerProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopFlowerServer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/StopFlowerServer",
            worker__pb2.StopFlowerProcessRequest.SerializeToString,
            worker__pb2.StopFlowerProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GarbageCollect(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/GarbageCollect",
            worker__pb2.GarbageCollectRequest.SerializeToString,
            worker__pb2.GarbageCollectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RunUdf(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/exaflow.worker.api.WorkerService/RunUdf",
            worker__pb2.RunUdfRequest.SerializeToString,
            worker__pb2.RunUdfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
