# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aggregator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x61ggregator.proto\x12\naggregator">\n\x10\x43onfigureRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x16\n\x0enum_of_workers\x18\x02 \x01(\x05"#\n\x11\x43onfigureResponse\x12\x0e\n\x06status\x18\x01 \x01(\t"N\n\x10\x41ggregateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x18\n\x10\x63omputation_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02"#\n\x11\x41ggregateResponse\x12\x0e\n\x06result\x18\x01 \x03(\x02"$\n\x0e\x43leanupRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t"!\n\x0f\x43leanupResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xfc\x01\n\nAggregator\x12T\n\x15\x43onfigureAggregations\x12\x1c.aggregator.ConfigureRequest\x1a\x1d.aggregator.ConfigureResponse\x12H\n\tAggregate\x12\x1c.aggregator.AggregateRequest\x1a\x1d.aggregator.AggregateResponse\x12N\n\x13\x43leanupAggregations\x12\x1a.aggregator.CleanupRequest\x1a\x1b.aggregator.CleanupResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "aggregator_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CONFIGUREREQUEST"]._serialized_start = 32
    _globals["_CONFIGUREREQUEST"]._serialized_end = 94
    _globals["_CONFIGURERESPONSE"]._serialized_start = 96
    _globals["_CONFIGURERESPONSE"]._serialized_end = 131
    _globals["_AGGREGATEREQUEST"]._serialized_start = 133
    _globals["_AGGREGATEREQUEST"]._serialized_end = 211
    _globals["_AGGREGATERESPONSE"]._serialized_start = 213
    _globals["_AGGREGATERESPONSE"]._serialized_end = 248
    _globals["_CLEANUPREQUEST"]._serialized_start = 250
    _globals["_CLEANUPREQUEST"]._serialized_end = 286
    _globals["_CLEANUPRESPONSE"]._serialized_start = 288
    _globals["_CLEANUPRESPONSE"]._serialized_end = 321
    _globals["_AGGREGATOR"]._serialized_start = 324
    _globals["_AGGREGATOR"]._serialized_end = 576
# @@protoc_insertion_point(module_scope)
