apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exareme2-localworker
  namespace: {{ .Values.namespace }}
  labels:
    app: exareme2-worker
    nodeType: localworker
spec:
  serviceName: "exareme2-worker"
  replicas: {{ .Values.localnodes }}
  selector:
    matchLabels:
      app: exareme2-worker
      nodeType: localworker
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: exareme2-worker
        nodeType: localworker
    spec:
      {{ if not .Values.managed_cluster }}
      nodeSelector:
        worker: "true"
      {{ end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: nodeType
                operator: In
                values:
                - localworker
            topologyKey: kubernetes.io/hostname
      # HostPath volumes if hostPath selected
      {{ if not .Values.managed_cluster }}
      volumes:
        - name: db-data
          hostPath:
            path: {{ printf "%s/db" .Values.storage.hostPath.db.localworker }}
        - name: csv-data
          hostPath:
            path: {{ printf "%s/csvs" .Values.storage.hostPath.db.localworker }}
        - name: credentials
          hostPath:
            path: {{ printf "%s/credentials" .Values.storage.hostPath.db.localworker }}
      {{ end }}

      containers:
      - name: monetdb
        image: {{ .Values.exareme2_images.repository }}/exareme2_db:{{ .Values.exareme2_images.version }}
        # LIMITS REMOVED DUE TO MONETDB NOT SEEING THEM PROPERLY
        # resources:
        #  limits:
        #    memory: "{{ .Values.db.max_memory }}Mi"
        env:
        - name: LOG_LEVEL
          value: {{ .Values.log_level }}
        - name: MONETDB_NCLIENTS
          value: {{ mul .Values.max_concurrent_experiments .Values.localnodes | quote }}
        - name: MAX_MEMORY
          value: {{ mul .Values.db.max_memory 1048576 | quote }}
        - name: SOFT_RESTART_MEMORY_LIMIT
          value: {{ div (mul .Values.db.max_memory .Values.db.percentage_soft_memory_limit) 100 | quote }}
        - name: HARD_RESTART_MEMORY_LIMIT
          value: {{ div (mul .Values.db.max_memory .Values.db.percentage_hard_memory_limit) 100 | quote }}
        ports:
        - containerPort: 50000
        volumeMounts:
        - mountPath: /home/monetdb
          name: db-data
        - mountPath: /opt/data
          name: csv-data
        - mountPath: /opt/credentials
          name: credentials
        startupProbe:
          exec:
            command:
            - mclient
            - db
            - -s
            - "select 1;"
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - mclient
            - db
            - -s
            - "select 1;"
          periodSeconds: 30

      - name: db-importer
        image: {{ .Values.exareme2_images.repository }}/exareme2_mipdb:{{ .Values.exareme2_images.version }}
        env:
        - name: DB_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SQLITE_DB_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DB_PORT
          value: "50000"
        volumeMounts:
        - mountPath: /opt/data
          name: csv-data
        - mountPath: /opt/credentials
          name: credentials

      - name: rabbitmq
        image: {{ .Values.exareme2_images.repository }}/exareme2_rabbitmq:{{ .Values.exareme2_images.version }}
        env:
        - name: RABBITMQ_ADMIN_USER
          value: "user"
        - name: RABBITMQ_ADMIN_PASSWORD
          value: "password"
        - name: RABBITMQ_ADMIN_VHOST
          value: "user_vhost"
        - name: RABBITMQ_SLEEP_BEFORE_CONFIGURATION
          value: "30"
        ports:
        - containerPort: 5672
        startupProbe:
          exec:
            command:
              - rabbitmq-diagnostics
              - -q
              - check_port_connectivity
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command:
              - rabbitmq-diagnostics
              - -q
              - check_port_connectivity
          periodSeconds: 30
          timeoutSeconds: 10

      - name: worker
        image: {{ .Values.exareme2_images.repository }}/exareme2_worker:{{ .Values.exareme2_images.version }}
        volumeMounts:
        - mountPath: /opt/credentials
          name: credentials
        - mountPath: /opt/data
          name: csv-data
        env:
        - name: WORKER_IDENTIFIER
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: WORKER_ROLE
          value: "LOCALWORKER"
        - name: FEDERATION
          value: {{ .Values.federation }}
        - name: LOG_LEVEL
          value: {{ .Values.log_level }}
        - name: FRAMEWORK_LOG_LEVEL
          value: {{ .Values.framework_log_level }}
        - name: CONTROLLER_IP
          value: $(EXAREME2_CONTROLLER_SERVICE_SERVICE_HOST)
        - name: CONTROLLER_PORT
          value: $(EXAREME2_CONTROLLER_SERVICE_SERVICE_PORT)
        - name: PROTECT_LOCAL_DATA
          value: "true"
        - name: CELERY_TASKS_TIMEOUT
          value: {{ quote .Values.controller.celery_tasks_timeout }}
        - name: RABBITMQ_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RABBITMQ_PORT
          value: "5672"
        - name: MONETDB_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MONETDB_PORT
          value: "50000"
        - name: MONETDB_LOCAL_USERNAME
          value: "executor"
        - name: MONETDB_LOCAL_PASSWORD
          value: "executor"
        - name: MONETDB_PUBLIC_USERNAME
          value: "guest"
        - name: MONETDB_PUBLIC_PASSWORD
          value: "guest"
        - name: SQLITE_DB_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SMPC_ENABLED
          value: {{ quote .Values.smpc.enabled }}
        {{ if .Values.smpc.enabled }}
        - name: SMPC_OPTIONAL
          value: {{ quote .Values.smpc.optional }}
        - name: SMPC_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SMPC_CLIENT_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SMPC_CLIENT_ADDRESS
          value: "http://$(SMPC_CLIENT_IP):9000"
        {{ end }}
        startupProbe:
          exec:
            command:
              - python
              - -m
              - exareme2.worker.healthcheck
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command:
              - python
              - -m
              - exareme2.worker.healthcheck
          periodSeconds: 30
          timeoutSeconds: 10

      {{ if .Values.smpc.enabled }}
      - name: smpc-client
        image: {{ .Values.smpc.image }}
        command: ["python", "client.py"]
        ports:
          - containerPort: 9000
        env:
        - name: ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PORT
          value: "9000"
        - name: COORDINATOR_IP
          value: exareme2-smpc-coordinator-service
        - name: COORDINATOR_URL
          value: "http://$(COORDINATOR_IP):12314"
        - name: PLAYER_IP_0
          value: exareme2-smpc-player0-service
        - name: PLAYER_REPO_0
          value: "http://$(PLAYER_IP_0):7000"
        - name: PLAYER_IP_1
          value: exareme2-smpc-player1-service
        - name: PLAYER_REPO_1
          value: "http://$(PLAYER_IP_1):7001"
        - name: PLAYER_IP_2
          value: exareme2-smpc-player2-service
        - name: PLAYER_REPO_2
          value: "http://$(PLAYER_IP_2):7002"
      {{ end }}

  {{ if .Values.managed_cluster }}
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        storageClassName: {{ .Values.storage.cephfs.storageClassName }}
        accessModes:
          - {{ index .Values.storage.cephfs.localworker.db.accessModes 0 }}
        resources:
          requests:
            storage: {{ .Values.storage.cephfs.localworker.db.size }}
    - metadata:
        name: csv-data
      spec:
        storageClassName: {{ .Values.storage.cephfs.storageClassName }}
        accessModes:
          - {{ index .Values.storage.cephfs.localworker.csvs.accessModes 0 }}
        resources:
          requests:
            storage: {{ .Values.storage.cephfs.localworker.csvs.size }}
    - metadata:
        name: credentials
      spec:
        storageClassName: {{ .Values.storage.cephfs.storageClassName }}
        accessModes:
          - {{ index .Values.storage.cephfs.localworker.creds.accessModes 0 }}
        resources:
          requests:
            storage: {{ .Values.storage.cephfs.localworker.creds.size }}
  {{ end }}
#---  # Used for SMPC cluster debugging
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: exareme2-worker-service
#  namespace: {{ .Values.namespace }}
#spec:
#  type: LoadBalancer
#  selector:
#    app: exareme2-worker
#  ports:
#    - protocol: TCP
#      port: 9000
#      targetPort: 9000
#      nodePort: 32000
