{{- if .Values.aggregation_server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exareme2-aggregation-server-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: exareme2-aggregation-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exareme2-aggregation-server
  template:
    metadata:
      labels:
        app: exareme2-aggregation-server
    spec:
      nodeSelector:
        master: "true"
      containers:
        - name: aggregation-server
          image: "{{ .Values.exareme2_images.repository }}/exareme2_aggregation_server:{{ .Values.exareme2_images.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: MAX_GRPC_CONNECTIONS
              # note: no outer quotes, and correct pipe-syntax
              value: {{ .Values.localnodes | int | mul .Values.max_concurrent_experiments | quote }}
            - name: MAX_WAIT_FOR_AGGREGATION_INPUTS
              value: {{ .Values.aggregation_server.max_wait_for_aggregation_inputs | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.log_level | quote }}
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            grpc:
              port: 50051
            periodSeconds: 15
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: exareme2-aggregation-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: exareme2-aggregation-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

{{- end }}
