apiVersion: apps/v1
kind: Deployment
metadata:
  name: exareme2-aggregation-server-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: exareme2-aggregation-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exareme2-aggregation-server
  template:
    metadata:
      labels:
        app: exareme2-aggregation-server
    spec:
      nodeSelector:
        master: "true"
      containers:
        - name: aggregator_server
          image: "{{ .Values.exareme2_images.repository }}/exareme2_aggregator:{{ .Values.exareme2_images.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: AGGREGATOR_HOST
              value: "0.0.0.0"
            - name: AGGREGATOR_PORT
              value: "50051"
            - name: AGGREGATOR_MAX_WORKERS
              value: "{{ .Values.aggregation_server.maxWorkers}}"
            - name: AGGREGATOR_TIMEOUT
              value: "{{ .Values.aggregation_server.timeout}}"
            - name: LOG_LEVEL
              value: "{{ .Values.log_level }}"
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            grpc:
              port: 50051
            periodSeconds: 15
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: exareme2-aggregation-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: exareme2-aggregation-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
