# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregation_server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18\x61ggregation_server.proto\x12\x12\x61ggregation_server">\n\x10\x43onfigureRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x16\n\x0enum_of_workers\x18\x02 \x01(\x05"W\n\x11\x43onfigureResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.aggregation_server.Status\x12\x16\n\x0estatus_message\x18\x02 \x01(\t"F\n\tOperation\x12\x18\n\x10\x61ggregation_type\x18\x01 \x01(\t\x12\x0f\n\x07vectors\x18\x02 \x03(\x01\x12\x0e\n\x06tensor\x18\x03 \x01(\x0c"g\n\x10\x41ggregateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\x31\n\noperations\x18\x03 \x03(\x0b\x32\x1d.aggregation_server.Operation"F\n\x11\x41ggregateResponse\x12\x0f\n\x07results\x18\x01 \x03(\x01\x12\x0f\n\x07offsets\x18\x02 \x03(\x05\x12\x0f\n\x07tensors\x18\x03 \x03(\x0c"$\n\x0e\x43leanupRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t"U\n\x0f\x43leanupResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.aggregation_server.Status\x12\x16\n\x0estatus_message\x18\x02 \x01(\t"\'\n\x11UnregisterRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t"s\n\x12UnregisterResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.aggregation_server.Status\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\x12\x19\n\x11remaining_workers\x18\x03 \x01(\x05*x\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x16\n\x12\x41LREADY_CONFIGURED\x10\x02\x12\r\n\tNOT_FOUND\x10\x03\x12\x0f\n\x0bMIN_WORKERS\x10\x04\x12\x0b\n\x07TIMEOUT\x10\x05\x12\t\n\x05\x45RROR\x10\x06\x32\xf8\x02\n\x11\x41ggregationServer\x12X\n\tConfigure\x12$.aggregation_server.ConfigureRequest\x1a%.aggregation_server.ConfigureResponse\x12[\n\nUnregister\x12%.aggregation_server.UnregisterRequest\x1a&.aggregation_server.UnregisterResponse\x12X\n\tAggregate\x12$.aggregation_server.AggregateRequest\x1a%.aggregation_server.AggregateResponse\x12R\n\x07\x43leanup\x12".aggregation_server.CleanupRequest\x1a#.aggregation_server.CleanupResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "aggregation_server_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_STATUS"]._serialized_start = 733
    _globals["_STATUS"]._serialized_end = 853
    _globals["_CONFIGUREREQUEST"]._serialized_start = 48
    _globals["_CONFIGUREREQUEST"]._serialized_end = 110
    _globals["_CONFIGURERESPONSE"]._serialized_start = 112
    _globals["_CONFIGURERESPONSE"]._serialized_end = 199
    _globals["_OPERATION"]._serialized_start = 201
    _globals["_OPERATION"]._serialized_end = 271
    _globals["_AGGREGATEREQUEST"]._serialized_start = 273
    _globals["_AGGREGATEREQUEST"]._serialized_end = 376
    _globals["_AGGREGATERESPONSE"]._serialized_start = 378
    _globals["_AGGREGATERESPONSE"]._serialized_end = 448
    _globals["_CLEANUPREQUEST"]._serialized_start = 450
    _globals["_CLEANUPREQUEST"]._serialized_end = 486
    _globals["_CLEANUPRESPONSE"]._serialized_start = 488
    _globals["_CLEANUPRESPONSE"]._serialized_end = 573
    _globals["_UNREGISTERREQUEST"]._serialized_start = 575
    _globals["_UNREGISTERREQUEST"]._serialized_end = 614
    _globals["_UNREGISTERRESPONSE"]._serialized_start = 616
    _globals["_UNREGISTERRESPONSE"]._serialized_end = 731
    _globals["_AGGREGATIONSERVER"]._serialized_start = 856
    _globals["_AGGREGATIONSERVER"]._serialized_end = 1232
# @@protoc_insertion_point(module_scope)
